services:
  - type: web
    name: ferramenta-pdf
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:asgi_app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
